extensions:
  basicauth/server:
    htpasswd:
      inline: |
        ${OTEL_USERNAME}:${OTEL_PASSWORD}

  health_check:

receivers:
  otlp:
    protocols:
      grpc:
        endpoint: 0.0.0.0:4317
        auth:
          authenticator: basicauth/server
      http:
        endpoint: 0.0.0.0:4318
        auth:
          authenticator: basicauth/server

processors:
  batch:

exporters:
  otlp/jaeger:
    endpoint: jaeger:4317
    tls:
      insecure: true

  prometheus:
    endpoint: 0.0.0.0:9090

  elasticsearch:
    endpoints: [https://elasticsearch:9200]
    user: elastic
    password: ${ELASTIC_PASSWORD}
    logs_index: otel-logs-%{+yyyy.MM.dd}
    tls:
      insecure: true

  debug:
    verbosity: detailed

service:
  extensions: [health_check, basicauth/server]

  pipelines:
    traces:
      receivers: [otlp]
      processors: [batch]
      exporters: [otlp/jaeger, debug]

    metrics:
      receivers: [otlp]
      processors: [batch]
      exporters: [prometheus, debug]

    logs:
      receivers: [otlp]
      processors: [batch]
      exporters: [elasticsearch, debug]
