services:
  elasticsearch:
    image: elasticsearch:9.1.2
    ports:
      - "9200:9200"
      - "9300:9300"
    environment:
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      - "ES_JAVA_OPTS=-Xms2g -Xmx2g"
    volumes:
      - elastic_data:/usr/share/elasticsearch/data
      - ./configs/elasticsearch.yaml:/usr/share/elasticsearch/config/elasticsearch.yaml
    healthcheck:
      test: ["CMD-SHELL", "curl -s --insecure --user elastic:${ELASTIC_PASSWORD} -X GET https://localhost:9200/_cluster/health | grep -q '\"status\":\"green\"\\|\"status\":\"yellow\"'"]
      interval: 15s
      timeout: 10s
      retries: 10
      start_period: 350s
    networks:
      - monitoring

  kibana:
    image: kibana:9.1.2
    ports:
      - "5601:5601"
    environment:
      - ELASTICSEARCH_HOSTS=https://elasticsearch:9200
      - ELASTICSEARCH_PASSWORD=${ELASTIC_PASSWORD}
    volumes:
      - ./configs/kibana.yaml:/usr/share/kibana/config/kibana.yaml:ro
    depends_on:
      elasticsearch:
        condition: service_healthy
    networks:
      - monitoring

  otel-collector:
    image: otel/opentelemetry-collector-contrib:latest
    ports:
      - "4317:4317"    # OTLP GRPC
      - "4318:4318"    # OTLP HTTP
      - "8889:8889"
    environment:
      - OTEL_USERNAME=${OTEL_USERNAME}
      - OTEL_PASSWORD=${OTEL_PASSWORD}
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      # - PROMETHEUS_PASSWORD=${PROMETHEUS_PASSWORD}
    volumes:
      - ./configs/otel-collector.yaml:/etc/otelcol-contrib/config.yaml
    depends_on:
      - elasticsearch
      - jaeger
    networks:
      - monitoring

  prometheus:
    image: prom/prometheus:latest
    ports:
      - "9090:9090"
    environment:
      - PROMETHEUS_USER=${PROMETHEUS_USER}
      - PROMETHEUS_PASSWORD=${PROMETHEUS_PASSWORD}
    volumes:
      - ./configs/prometheus.yaml:/etc/prometheus/prometheus.yaml
      - ./configs/prometheus.web.yaml:/etc/prometheus/web.yaml
    command:
      - '--config.file=/etc/prometheus/prometheus.yaml'
      - '--web.config.file=/etc/prometheus/web.yaml'
    networks:
      - monitoring

  jaeger:
    image: jaegertracing/jaeger:latest
    ports:
      - "16686:16686"   # UI
      - "14250:14250"   # gRPC for agent
      - "14268:14268"   # HTTP (optional)
    environment:
      - SPAN_STORAGE_TYPE=elasticsearch
      - ELASTIC_SERVER_URLS=https://elasticsearch:9200
      - ELASTIC_USERNAME=elastic
      - ELASTIC_PASSWORD=${ELASTIC_PASSWORD}
      # - JAEGER_PASSWORD
    networks:
      - monitoring

  # grafana:
  #   image: grafana/grafana:latest
  #   ports:
  #     - "3000:3000"
  #  environment:
  #     # - GF_AUTH_ANONYMOUS_ENABLED=true
  #     # - GF_AUTH_ANONYMOUS_ORG_ROLE=Admin
  #     - GF_SECURITY_ADMIN_USER=${GRAFANA_ADMIN_USER}
  #     - GF_SECURITY_ADMIN_PASSWORD=${GRAFANA_ADMIN_PASSWORD}
  #     - PROMETHEUS_USER=${PROMETHEUS_USER}
  #     - PROMETHEUS_PASSWORD=${PROMETHEUS_PASSWORD}
  #   volumes:
  #     - ./configs/grafana:/etc/grafana/provisioning/datasources
  #   depends_on:
  #     - prometheus
  #     - jaeger
  #   networks:
  #     - monitoring

volumes:
  elastic_data:

networks:
  monitoring:
    driver: bridge
