apiVersion: 1

datasources:
  - name: Prometheus
    type: prometheus
    access: proxy
    url: http://prometheus:9090
    isDefault: true
    basicAuth: true
    basicAuthUser: ${PROMETHEUS_USER}
    jsonData: {}
    secureJsonData:
      basicAuthPassword: ${PROMETHEUS_PASSWORD}

  - name: Jaeger
    type: jaeger
    access: proxy
    url: http://jaeger:16686
    jsonData: {}
