# --- Общие настройки ---
discovery.type: single-node

# --- Настройки безопасности ---
xpack.security.enabled: true
# xpack.security.autoconfiguration.enabled: false

xpack.security.http.ssl.enabled: false
xpack.security.transport.ssl.enabled: false

# --- Настройки SSL для HTTP Layer (порт 9200) ---
# xpack.security.http.ssl.enabled: true
# xpack.security.http.ssl.certificate: /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch.crt
# xpack.security.http.ssl.key: /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch.key
# xpack.security.http.ssl.certificate_authorities: /usr/share/elasticsearch/config/certs/ca/ca.crt

# --- Настройки SSL для Transport Layer (порт 9300) ---
# xpack.security.transport.ssl.enabled: true
# xpack.security.transport.ssl.certificate: /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch.crt
# xpack.security.transport.ssl.key: /usr/share/elasticsearch/config/certs/elasticsearch/elasticsearch.key
# xpack.security.transport.ssl.certificate_authorities: /usr/share/elasticsearch/config/certs/ca/ca.crt

# --- Ваши дополнительные настройки ---
action.auto_create_index: "otel-logs-*,otel-traces-*,otel-metrics-*"
